=== hectormaoglb/instafeed/validator/article.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://nodeacademy.globant.com/article.schema.json",
    "title": "Article",
    "description": "Article Schema",
    "type": "object",
    "properties": {
        "id": {
          "description": "Unique ID's Article",
          "type": "string",
          "minLength": 36,
          "maxLength": 36,
          "pattern": "^(?!\\s*$).+"
        }, 
        "title": {
            "description": "Title's Article",
            "type": "string",
            "minLength": 1,
            "maxLength": 255,
            "pattern": "^(?!\\s*$).+"
        },
        "author": {
            "description": "Author's Article",
            "type": "string",
            "minLength": 1,
            "maxLength": 100,
            "pattern": "^(?!\\s*$).+"
        },
        "modifiedAt": {
            "description": "Creation or Modification Date",
            "type": "string",
            "pattern": "^\\d{2}/\\d{2}/\\d{4}$"
        },
        "publishedAt": {
            "description": "Publish Date",
            "type": "string",
            "pattern": "^\\d{2}/\\d{2}/\\d{4}$"
        },
        "url": {
            "description": "URL's Article",
            "type": "string",
            "pattern": "^https://.*$"
        },
        "keywords": {
            "description": "Keyword's Article",
            "type": "array",
            "items": {
                "type": "string"
            },
            "minItems": 1,
            "maxItems": 3
        },
        "readMins": {
            "description": "time to read in mins",
            "type": "number",
            "minimum": 1,
            "maximum": 20
        },
        "source": {
            "description": "Platform source",
            "type": "string",
            "enum": ["ARTICLE", "BLOG", "TWEET", "NEWSPAPER"]
        }
      },
      "required": [ "id", "title", "author", "modifiedAt", "keywords", "readMins", "source" ],
      "additionalProperties": false
  }

=== hectormaoglb/instafeed/article.json
{
    "id": "This is a valid id with 36 character",
    "title": "Article Title",
    "author": "Article Author",
    "modifiedAt": "01/01/2021",
    "publishedAt": "01/01/2021",
    "url": "https://www.google.com",
    "keywords": ["word1", "word2", "word3"],
    "readMins": 10,
    "source": "ARTICLE"
}

=== hectormaoglb/instafeed/test/fixtures/validArticle.json
{
  "id": "2d77b0c6-858f-407f-a518-58371ac9adcb",
  "title": "Promises in Node.js",
  "url": "https://www.geeksforgeeks.org/promises-in-node-js/",
  "keywords": ["JavaScript", "Async"],
  "modifiedAt": "07/13/2019",
  "publishedAt": "07/13/2019",
  "author": "03607f01-b038-4b46-9b17-50733843888f",
  "readMins": 3,
  "source": "BLOG"
}
